[build]
  command = "gatsby build"
  #functions = "functions"
  publish = "public"

  [[redirects]]
 from = "/*"
to = "/index.html"

  [[redirects]]
from= "/app/admin.js "
to=  "/app"

  [[redirects]]
from= "/app/login"
to= "/app"